<?php

namespace App\Models;

use App\Enums\ReminderType;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class Reminder
 *
 * Represents a system-generated reminder for an HR action item.
 * Reminders are generated by evaluator services registered within {@see \App\Services\Reminder\ReminderService}.
 *
 * @property int                                  $id
 * @property ReminderType                         $type           Machine-readable reminder category.
 * @property string                               $title          Short display title.
 * @property string|null                          $message        Optional longer context message.
 * @property string                               $related_type   Polymorphic model class (e.g., App\Models\Contract).
 * @property int                                  $related_id     Polymorphic model ID.
 * @property string                               $remind_at      Datetime when this reminder becomes relevant.
 * @property string|null                          $deadline_at    Datetime deadline for this reminder.
 * @property string                               $status         One of: pending, critical, missed, done.
 * @property \Illuminate\Support\Carbon|null      $dismissed_at   When an admin dismissed this reminder.
 * @property \Illuminate\Support\Carbon|null      $created_at
 * @property \Illuminate\Support\Carbon|null      $updated_at
 */
class Reminder extends Model
{
    use HasFactory;

    protected $table = 'reminders';

    /** @var array<int, string> */
    protected $fillable = [
        'type',
        'title',
        'message',
        'related_type',
        'related_id',
        'remind_at',
        'deadline_at',
        'status',
        'dismissed_at',
    ];

    /** @var array<string, string> */
    protected $casts = [
        'type'         => ReminderType::class,
        'remind_at'    => 'datetime',
        'deadline_at'  => 'datetime',
        'dismissed_at' => 'datetime',
    ];

    /**
     * Get the related model (e.g., Contract, Worker) for this reminder.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function related()
    {
        return $this->morphTo();
    }

    /**
     * Scope to only active (non-dismissed) reminders.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->whereNull('dismissed_at');
    }

    /**
     * Scope to only dismissed reminders.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeDismissed($query)
    {
        return $query->whereNotNull('dismissed_at');
    }
}
